version: '3.8'

services:
  app:
    build: .
    expose:
      - 8000
    command: uwsgi --ini app.ini
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always
